name: build

on:

  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        device: [g84_gdx] #g84_ftx
    name: "🚧 Build for ${{matrix.device}}"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Paris"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install bison flex libssl-dev libarchive-tools git -y

      - name: Setup Toolchains
        run: |
          mkdir -p toolchain
          cd toolchain
          echo 'Download AOSP Toolchain'
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 --depth 1 -b master clang-latest
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 --depth 1
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 --depth 1
          echo 'Done'

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 30

      - name: Run build
        run: |
          DEVICE=${{matrix.device}} ./build.sh

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: LineageOS_Custom-${{matrix.device}}
          path: AnyKernel3/O*.zip
