name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        device: [g84_gdx] #g84_fts

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            binutils \
            bc \
            bison \
            flex \
            libssl-dev \
            ccache \
            python3 \
            zip

      - name: Clone Proton Clang
        run: |
          mkdir -p toolchain
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git toolchain/proton-clang

      - name: Toolchain diagnostic
        run: |
          which ld
          ld --version
          toolchain/proton-clang/bin/clang --version
          toolchain/proton-clang/bin/ld.lld --version

      - name: Build Kernel
        run: |
          chmod +x build.sh
          DEVICE=${{ matrix.device }} ./build.sh -d

      - name: Build AnyKernel3 Flashable ZIP
        run: |
          # DEVICE=${{ matrix.device }} ./build_zip.sh -d
          echo "Insha Allah this will works in the future :D"

      - name: Upload AnyKernel3 ZIP File
        uses: actions/upload-artifact@v4
        with:
          name: LineageOS_ProtonClang-${{matrix.device}}-${{ github.run_id }}
          path: "*.zip"
      
      - name: Archive out directory
        run: |
          zip -r kernel_out_full.zip out/

      - name: Upload Full Out Directory
        uses: actions/upload-artifact@v4
        with:
          name: Full-Out-Directory-${{ matrix.device }}
          path: kernel_out_full.zip
          retention-days: 5 # Optionnel : limite la durée de stockage pour économiser ton quota

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: Image
          path: "out/arch/arm64/boot/Image"
